/**
 * Region Behavior type: a weapon's on-hit "region" (areaOfEffect) - a static
 * shape placed centered on the target at the moment of a hit, which does NOT
 * follow the target afterward (unlike PowerAuraRegionBehaviorType, which is
 * always attached to its owner's token). See utils/area-of-effect.ts for
 * creation and utils/power-aura.ts's tickPowerAuraRegions sibling,
 * tickWeaponAreaEffectRegions, for expiry and per-round damage-over-time
 * ticking against whoever is currently standing inside.
 *
 * Carries independent, entirely optional effects copied from the triggering
 * weapon's own configuration at the moment the region is created - reusing
 * config a GM already set up on the weapon rather than adding a second,
 * separate configuration surface for the region itself. Every enabled entry
 * on the weapon becomes its OWN entry here, tracked and expiring
 * independently (each with its own rolled duration), even though they all
 * live on this single region:
 *
 * - dots: one entry per enabled `dots` entry on the weapon (rank/
 *   armorPiercing), each ticked every round against anyone currently
 *   standing inside (see tickWeaponAreaEffectRegions).
 * - resolvedStatShifts/resolvedDamageShifts: one entry per enabled
 *   statDebuffs/damageBuffs entry on the weapon, each resolved against the
 *   SAME attack roll that triggered the hit (same green/yellow/red tier the
 *   direct hit target's own debuff used) and given its own rolled duration
 *   from that entry's durationFormula - live-summed at the moment of a roll
 *   via getWeaponAreaEffectStatShift/getWeaponAreaEffectDamageShift, exactly
 *   like PowerAuraRegionBehaviorType's resolved shifts, just without an
 *   owner/disposition filter (a blast doesn't discriminate) and per-entry
 *   instead of pre-summed, so one debuff expiring doesn't affect another.
 *
 * A region can have any combination of these, or none (in which case it's
 * just a visual marker on the scene).
 *
 * Bookkeeping (sourceWeaponName/indefinite/roundsRemaining for the region's
 * OWN overall lifetime) lives in flags.faserip, not this schema, for the
 * same reason as PowerAuraRegionBehaviorType - it's internal linkage, not
 * something a GM would hand-edit from the region behavior config sheet.
 *
 * `summary` is a plain, human-readable restatement of dots/
 * resolvedStatShifts/resolvedDamageShifts, regenerated by
 * utils/area-of-effect.ts every time those arrays are set or ticked. It
 * exists purely so the GM can actually SEE what's on this region from the
 * stock RegionBehaviorConfig sheet - Foundry's default sheet template has no
 * built-in editor for an ArrayField of SchemaFields, so the three real
 * tracking fields above render as nothing there even though they're fully
 * functional; a plain StringField renders fine. Editing it by hand has no
 * effect - it's overwritten the next time the underlying arrays change.
 */
const { StringField, NumberField, BooleanField, ArrayField, SchemaField } =
  foundry.data.fields;

export class WeaponAreaEffectRegionBehaviorType extends foundry.data.regionBehaviors.RegionBehaviorType {
  static override LOCALIZATION_PREFIXES = [
    "FASERIP.BEHAVIOR.TYPES.weaponAreaEffect"
  ];

  static override defineSchema() {
    return {
      events: this._createEventsField({
        events: ["tokenEnter", "tokenExit"],
        initial: []
      }),
      dots: new ArrayField(
        new SchemaField({
          rank: new StringField({ required: false, blank: true, initial: "" }),
          armorPiercing: new StringField({
            required: false,
            blank: true,
            initial: ""
          })
        }),
        { required: false, initial: [] }
      ),
      resolvedStatShifts: new ArrayField(
        new SchemaField({
          attribute: new StringField({ required: false, initial: "intuition" }),
          chartShift: new NumberField({
            required: false,
            integer: true,
            initial: 0
          }),
          indefinite: new BooleanField({ required: false, initial: false }),
          roundsRemaining: new NumberField({
            required: false,
            integer: true,
            initial: 0
          })
        }),
        { required: false, initial: [] }
      ),
      resolvedDamageShifts: new ArrayField(
        new SchemaField({
          chartShift: new NumberField({
            required: false,
            integer: true,
            initial: 0
          }),
          indefinite: new BooleanField({ required: false, initial: false }),
          roundsRemaining: new NumberField({
            required: false,
            integer: true,
            initial: 0
          })
        }),
        { required: false, initial: [] }
      ),
      summary: new StringField({ required: false, blank: true, initial: "" })
    };
  }
}
